test/unit/StringTest.cpp

Since `PdfString` is in the `PoDoFo` namespace, the `operator<<` for it must be in the
same namespace as well, otherwise it is not found. In particular,
`operator<<(std::ostream&)` is needed by cppunit as a way to get the
string representation of an arbitrary type, when using
`CPPUNIT_ASSERT_EQUAL()` on instances of it.
This used to work with GCC until 11 because of a buggy behaviour.
GCC 12 fixed it [1], causing this test to fail to build with it.
[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51577

Fix declaration of `operator<<` for `PoDoFo::PdfString`

---

src/podofo/base/PdfDate.cpp
test/unit/DateTest.cpp
test/unit/DateTest.h

When DTS is not included in offset Acrobat Reader displays Creation Time one hour in future (for CEST timezone).

Fix timezone information. Offset must include DST.

---

CMakeLists.txt

Hello again.
This PR fixes minor issue when `PoDoFo` included into project as 3rdparty directory. In this case somebody in his `CMakeLists.txt` may do the following:
```cmake
set( PODOFO_BUILD_LIB_ONLY ON CACHE INTERNAL "" FORCE )
set( PODOFO_SHARED ON CACHE INTERNAL "" FORCE )
add_subdirectory( 3rdparty/podofo )
```
And if user builds his project with custom `CMAKE_MODULE_PATH` it will be overwritten in `3rdparty/podofo` and something can be not found. Whereas adding `"${CMAKE_MODULE_PATH}"` enlarges paths...

Enlarge CMAKE_MODULE_PATH instead of overwritting.

---

src/podofo/main/PdfFontMetricsObject.cpp

Example file used with `podofotxtextract`: [invalid_font.pdf](https://github.com/podofo/podofo/files/10732592/invalid_font.pdf)

avoid nullptr dereference in font metrics creation

---

src/podofo/main/PdfParser.cpp

I am not sure claiming “no trailer” is the most useful error to throw here. But relying on an assertion seems just wrong when there is an input file we know triggers the case (cf. pull request #50, which kept the assertion in).

avoid nullptr dereference if trailer has not been loaded

---

src/podofo/auxiliary/basetypes.h

* Explicitly compare as `std::string_view`, `const std::string&`, or `const char*`
* Allow the compiler to figure out `operator==` instead of forcing `std::operator==` 
* Use static_cast instead of C-style casting (reinterpret_cast)
* Add noexcept where appropriate
Using gcc 13.1.1 on Arch Linux I get the following errors with this program:
```c++
#include <podofo/podofo.h>
int main() { return 0; }
```
```
g++ -std=c++20 test.cpp
In file included from /usr/include/podofo/auxiliary/StreamDevice.h:15,
from /usr/include/podofo/podofo.h:22,
from test.cpp:1:
/usr/include/podofo/auxiliary/basetypes.h: In function ‘bool PoDoFo::operator==(const char*, const charbuff_t<>&)’:
/usr/include/podofo/auxiliary/basetypes.h:96:31: error: no matching function for call to ‘operator==(const char*&, …
```

Fix operator== for charbuff_t<> in C++20

---

src/podofo/main/PdfDocument.cpp
src/podofo/private/charconv_compat.h

This is a fix for issue #76, along with a fix to allow compilation with clang14 on linux by adding noexcept to one of the functions (see the commit). The commits are separate in case you don't want one or the other.

Fix issue #76 and add noexcept to from_chars function declaration to allow compilation on linux with clang14

---

src/podofo/main/PdfObjectStream.h

PdfObjectStream, a PODOFO_API exported class, has public methods GetInputStream and GetOutputStream returning PdfObjectInputStream and PdfObjectOutputStream instances. Consequently the caller code needs to be able to call the destructor of those classes, and their public methods. Currently there is a linking error related to that.

Export PdfObjectInputStream and PdfObjectOutputStream with PODOFO_API

---

src/podofo/main/PdfXMPPacket.cpp
src/podofo/private/XmlUtils.h

fix #112 
_should_ be backwards compatible but I haven't tested it, so relying on the CI here.

fix compilation with libxml 2.12.0

---

man/CMakeLists.txt

Apparently MANDIR is no longer set by the parent CMakeLists.txt, so this is not only a good idea, it's necessary.
of the LGPL 2.0 or later
of the MPL 2.0
of the MIT-0

Install man pages in directory from GNUInstallDirs

---

src/podofo/private/OpenSSLInternal.cpp

Otherwise crashes on linux in dtor
- [ x] Accept to license the library and tools code under the terms
- [ x] Accept to license the library and tools code under the terms
- [ x] Accept to license the test code under the terms
- [ x] Read [contributions](https://github.com/podofo/podofo#contributions) guidelines
- [ x] Checked coding [style](https://github.com/podofo/podofo/blob/master/CODING-STYLE.md)
- [ x] The commits sequence is clean without work in progress/bugged revisions and merge commits. In doubt, [squash](https://github.com/podofo/podofo/wiki/Squash-git-history-guide) the commits and/or rebase …

Free the SSL context after unloading the provider libs

---

src/podofo/main/PdfEncoding.cpp
src/podofo/main/PdfEncodingMap.cpp

I found an error in the size of codespacerange when the size of the ranges variable is not 1.
This error generates an illegal cmap stream causing the acrobat reader to not parse the PDF properly.

Fix incorrect cmap codespacerange size

---

src/podofo/main/PdfDocument.cpp

- [ x] Accept to license the library and tools code under the terms
- [ x] Accept to license the library and tools code under the terms
- [ x] Accept to license the test code under the terms
- [ x] Read [contributions](https://github.com/podofo/podofo#contributions) guidelines
- [ x] Checked coding [style](https://github.com/podofo/podofo/blob/master/CODING-STYLE.md)
- [ x] The commits sequence is clean without work in progress/bugged revisions and merge commits. In doubt, [squash](https://github.com/podofo/podofo/wiki/Squash-git-history-guide) the commits and/or rebase master
The fix in the commit 202f6af …

Fixes for InsertDocumentPageAt

---

README.md

I assume the same change should also be done for the other build descriptions, but I have no way to check.

`brew` should also install `cmake` if needed

---

src/podofo/main/PdfObject.cpp

This triggers `-fsanitize=undefined` while creating a `PdfMemDocument`. No test point added because I don't think there's any tests running with sanitizers right now, and existing tests do go through these lines.

Fix Typo: Do not call `GetDictionaryUnsafe` for `Array`

---

src/podofo/main/PdfPainter.cpp

When using the painter.DrawTextMultiLine with multi line text and non-left-aligned text,
the first line is correctly positioned, the following lines are not.
The pull requests fixed the alignment issue.
There is still a white space at the end of the lines, this is not fixed with this pull request.
Manually breaking with \n works.

fixed offset on multiline text if text is not left aligned

---

src/podofo/main/PdfPainter.cpp
test/unit/PainterTest.cpp

Recreate (cherrypick) #196 for master
--

Fix text underline (and probably strike-through) incompatibility with poppler

---

src/podofo/main/PdfCharCodeMap.cpp

When using `PdfPage::ExtractTextTo` on PDFs like [this](https://github.com/user-attachments/files/17973374/crash.pdf), the program would occasionally crash with a null pointer dereference. The crash appears to occur on this line:
https://github.com/podofo/podofo/blob/bc19d27c95c42d899bb76118542cc49cbb84d04a/src/podofo/main/PdfCharCodeMap.cpp#L396
Due to how `std::shuffle` is implemented, the above line could result in a swap on the same element of `mappings`, which will cause a self-assignment on the `CodePointSpan` object. This situation is not handled correctly by `CodePointSpan::operator=`. If the data of `CodePointSpan` is sufficiently large to be stored on the heap, self-assignment will invoke the `unique_ptr`'s destructor and reset the pointer to null, causing a subsequent segfault …

CodePointSpan: Protect against self-assignment

---

src/podofo/main/PdfTextState.cpp

Just noticed this while using the function, seems to eat non-space chars. This seems to fix it.
(Since we need to focus on finishing required features atm I don’t have time to write tests for this or validate the solution further).
Might be related to #111 
--

Fix eating of non-space chars in SplitTextAsLines

---

src/podofo/main/PdfPage.h
src/podofo/main/PdfPage_TextExtraction.cpp
test/unit/TextExtraction.cpp

Avoid function that loop endlessly or take too long
When using `PoDoFo` to process some abnormal or non-compliant PDF files, it may result in an infinite loop. The same issue occurs when I test these abnormal PDFs using `Poppler`. Therefore, I referred to the approach used by `Poppler` and added an abort check callback function, allowing the caller to control the exit from `PdfPage::ExtractTextTo`. 

PdfPage: Add abort check in PdfPage::ExtractTextTo

---

src/podofo/main/PdfEncoding.cpp

This took me 15 hours to debug... When you have the newest .NET Framework update in Windows (it’s right now being delivered via Windows Update) then Microsoft Edge’s text rendering breaks with podofo generated PDFs and this was the reason :scream:

Fix Edge text rendering bug (text disappears) by placing CMap directly after slash

---

src/podofo/private/charconv_compat.h

LLVM libc++ starts to provide a float-point-capable std::from_chars() since LLVM 20 release. Unconditionally defining from_chars() when using Clang will cause ambiguous references and fails the build.
Link: https://github.com/llvm/llvm-project/pull/91651 # [1]

private: charconv: Don't define from_chars for libc++ 20 or later

---

src/podofo/main/PdfImage.cpp

This code does not depend on PNG and is used in PODOFO_HAVE_PNG_LIB=FALSE code.
Fixes #271

Move `PdfImage::getTransformation` outside `#if PODOFO_HAVE_PNG_LIB`

---

src/podofo/main/PdfPage_TextExtraction.cpp
test/unit/TextExtraction.cpp

Fix the order of operations for the quote and double-quote operators: They ahould start a new line first, and then parse the text.
Fixes #278

`'` and `"` mean “`T*`, and *then* Tj”
